# Desafio: Sistema de Conta Bancária

## Regras:
- Classe `ContaBancaria`: titular, saldo
- Métodos: `depositar()`, `sacar()`, `exibirSaldo()`
- Criar herança para `ContaPoupanca` com limite de saques mensais

## Extras:
- Usar `data class` para registrar transações


In [47]:
import java.time.LocalDate

enum class Metodo{
    SAQUE,
    DEPOSITO,
}

data class Transacao(var value:Double, var metodo: Metodo, var data: LocalDate)

open class ContaBancaria(
    protected var titular: String,
    protected var saldo: Double,
    protected var transacoes: MutableList<Transacao> = mutableListOf()
){
     fun depositar(value:Double) {
        println("Titular: $titular Está efetuando um Deposito:")
        if (value <= 0){
            println("Digite um valor válido para deposito")
            return
        }
        this.saldo += value
        this.transacoes.add(Transacao(value,Metodo.DEPOSITO,LocalDate.now()))

        println("Deposito no valor de R$ $value efetuado com sucesso saldo atual : ${this.saldo}\n")
    }

    open fun sacar(value:Double) {
        if (value > this.saldo){
            println("Saldo insuficiente para o saque")
        }
        this.saldo -= value
        this.transacoes.add(Transacao(value,Metodo.SAQUE,LocalDate.now()))
        println("Titular: $titular Está efetuando um Saque:")
        println("Saque no valor de R$ $value efetuado com sucesso saldo atual : ${this.saldo}\n")
    }

    fun exibirSaldo() {
        println("Saldo Atual do Titular ${this.titular}: R$ ${this.saldo}")
    }
}

class ContaPoupanca(titular: String, saldo:Double) : ContaBancaria(titular, saldo) {

    override fun sacar(value:Double) {
        println("Titular: $titular  Está efetuando um Saque da conta Poupança:")

        val limite = 3 ;

        if (value > this.saldo){
            println("Saldo insuficiente para o saque")
            return
        }

        val saques = transacoes.filter { it.metodo.equals(Metodo.SAQUE) }
        val ultimosSaques = saques.filter { it.data.month == LocalDate.now().month }

        if ( ultimosSaques.size >= limite) {
            println("Limite de Saques Mensais atingidos")
            return
        }

        this.saldo -= value
        this.transacoes.add(Transacao(value,Metodo.SAQUE,LocalDate.now()))

        println("Saque no valor de R$ $value efetuado com sucesso saldo atual : ${this.saldo}")
    }
}

var Conta = ContaBancaria("Vitor",200.00)
var Poupança = ContaPoupanca("Vitin",200.00)

Conta.depositar(200.00)
Conta.sacar(200.00)
Conta.exibirSaldo()




Titular: Vitor Está efetuando um Deposito:
Deposito no valor de R$ 200.0 efetuado com sucesso saldo atual : 400.0

Titular: Vitor Está efetuando um Saque:
Saque no valor de R$ 200.0 efetuado com sucesso saldo atual : 200.0

Saldo Atual do Titular Vitor: R$ 200.0


# Console
```text
Titular: Vitor Está efetuando um Deposito:
Deposito no valor de R$ 200.0 efetuado com sucesso saldo atual : 400.0

Titular: Vitor Está efetuando um Saque:
Saque no valor de R$ 200.0 efetuado com sucesso saldo atual : 200.0

Saldo Atual do Titular Vitor: R$ 200.0
````